'use strict';

import { sessionRequest, getSession, registryRequest, uploadSignature } from './api-client.js';
import { state, resetCache, hasCapability, scopeText } from './state.js';
import { $, $$, esc, requestId, toast } from './format.js';
import * as pages from './pages.js';

const titles={dashboard:'Dashboard',students:'Students',staff:'Staff',registrations:'Staff registrations',allocations:'Class / Subject Allocation',portalAccess:'Portal Access',calendar:'Academic Calendar',portfolio:'Portfolio'};
let selectedPersonId='';
let pendingAllocationEnd=null;

const SSO_TRANSACTION_KEY='wts_central_registry_pkce_transaction';
const SSO_CLIENT_ID='central_registry';
const SSO_PORTAL_ORIGIN=String(window.WTS_PORTAL_ORIGIN || 'https://wts-school-platform.vercel.app').replace(/\/$/,'');
const SSO_REGISTRY_ORIGIN=String(window.WTS_REGISTRY_ORIGIN || 'https://wts-central-registry.vercel.app').replace(/\/$/,'');
const SSO_REDIRECT_URI=`${SSO_REGISTRY_ORIGIN}/`;

function base64Url(bytes){let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return base64Url(bytes);}
async function codeChallenge(verifier){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return base64Url(new Uint8Array(digest));}
function saveSsoTransaction(transaction){sessionStorage.setItem(SSO_TRANSACTION_KEY,JSON.stringify(transaction));}
function loadSsoTransaction(){try{const transaction=JSON.parse(sessionStorage.getItem(SSO_TRANSACTION_KEY) || 'null');if(!transaction || !transaction.verifier || !transaction.state || !transaction.nonce || Number(transaction.expires_at)<=Date.now())return null;return transaction;}catch{return null;}}
function clearSsoTransaction(){sessionStorage.removeItem(SSO_TRANSACTION_KEY);}
async function beginSso(){
  if(window.__WTS_CENTRAL_SSO_PENDING)return;
  window.__WTS_CENTRAL_SSO_PENDING=true;
  $('#authError').textContent='Opening your School Workspace session…';
  const verifier=randomToken();const stateToken=randomToken();const nonce=randomToken();const challenge=await codeChallenge(verifier);
  saveSsoTransaction({verifier,state:stateToken,nonce,expires_at:Date.now()+5*60*1000});
  const authorize=new URL(`${SSO_PORTAL_ORIGIN}/api/sso/authorize`);
  authorize.searchParams.set('response_type','code');authorize.searchParams.set('client_id',SSO_CLIENT_ID);authorize.searchParams.set('redirect_uri',SSO_REDIRECT_URI);authorize.searchParams.set('scope','central_registry');authorize.searchParams.set('code_challenge',challenge);authorize.searchParams.set('code_challenge_method','S256');authorize.searchParams.set('state',stateToken);authorize.searchParams.set('nonce',nonce);
  window.location.assign(authorize.toString());
}
async function exchangeSsoCallback(){
  const query=new URLSearchParams(window.location.search);const returnedError=query.get('error') || query.get('code_error');
  if(returnedError)throw Object.assign(new Error(returnedError),{code:returnedError});
  const code=query.get('code');const returnedState=query.get('state');const returnedNonce=query.get('nonce');
  if(!code && !returnedState && !returnedNonce)return null;
  const transaction=loadSsoTransaction();
  if(!code || !returnedState || !returnedNonce || !transaction || returnedState!==transaction.state || returnedNonce!==transaction.nonce){clearSsoTransaction();throw Object.assign(new Error('SSO_CALLBACK_INVALID'),{code:'SSO_CALLBACK_INVALID'});}
  const result=await sessionRequest({action:'sso_exchange',grant_type:'authorization_code',client_id:SSO_CLIENT_ID,redirect_uri:SSO_REDIRECT_URI,code,state:returnedState,nonce:returnedNonce,code_verifier:transaction.verifier});
  clearSsoTransaction();window.history.replaceState({},document.title,`${window.location.pathname}${window.location.hash}`);return result;
}

function showError(error) { const code=error?.code || error?.message || 'REGISTRY_REQUEST_FAILED'; toast(code,'error'); if (error?.status===401) lock(); }
function lock() { state.context=null; selectedPersonId=''; resetCache(); document.body.classList.add('locked'); $('#registryShell').hidden=true; $('#authGate').hidden=false; $('#loginPassword').value=''; $('#loginName').focus(); }
function applyContext(context) { state.context=context; document.body.classList.remove('locked'); $('#authGate').hidden=true; $('#registryShell').hidden=false; $('#actorLine').textContent=`${context.actor?.fullName || 'Staff'} · ${context.actor?.staffNumber || ''} · ${scopeText()}`; $('#scopeNotice').textContent=scopeText(); $('#scopeNotice').hidden=false; configureNav(); }
function configureNav() { const show=(route,yes)=>{const node=document.querySelector(`[data-route="${route}"]`);if(node)node.hidden=!yes;}; show('students',hasCapability('students.school.read')||hasCapability('students.stage.read')||hasCapability('students.class.read'));show('staff',hasCapability('staff.school.read')||hasCapability('staff.stage.read')||true);show('allocations',hasCapability('allocations.read'));show('portalAccess',hasCapability('portal_access.manage'));show('calendar',hasCapability('academic_calendar.read'));show('portfolio',true);show('registrations',hasCapability('staff.school.read')); }
async function loadRoute(route,force=false) { state.route=route; $$('.registry-page').forEach((page)=>page.classList.toggle('active',page.dataset.page===route)); $$('.registry-sidebar [data-route]').forEach((button)=>button.classList.toggle('active',button.dataset.route===route)); $('#pageTitle').textContent=titles[route] || 'Central Registry'; if(force) resetCache(); try { if(route==='dashboard') await pages.loadDashboard(); else if(route==='students') await pages.loadStudents(); else if(route==='staff') await pages.loadStaff(); else if(route==='registrations') await pages.loadRegistrations(); else if(route==='allocations') await pages.loadAllocations(); else if(route==='portalAccess') await pages.loadPortalAccess(); else if(route==='calendar') await pages.loadCalendar(); else if(route==='portfolio') await pages.loadPortfolio(); } catch(error){showError(error);} }
async function loadContext() { const context=await getSession(); applyContext(context); await loadRoute(state.route || 'dashboard',true); }
async function write(action,payload={}) { try { const result=await registryRequest('write',action,{...payload,requestId:payload.requestId || requestId()}); toast(result.code || 'Saved','success'); resetCache(); await loadContext(); return result; } catch(error){ showError(error); throw error; } }
function openStudentDialog(student={},mode='edit') {
  const dialog=$('#recordDialog');const isRestore=mode==='restore';
  $('#dialogTitle').textContent=student.id?(isRestore?'Restore student':'Update student'):'Admit student';$('#dialogError').textContent='';
  $('#dialogBody').innerHTML=`<label class="full">Full name<input name="name" maxlength="160" required value="${esc(student.name || '')}" ${isRestore?'readonly':''}></label><label>Gender<select name="gender" ${isRestore?'disabled':''}><option value="">Select</option><option value="male" ${String(student.gender).toLowerCase()==='male'?'selected':''}>Male</option><option value="female" ${String(student.gender).toLowerCase()==='female'?'selected':''}>Female</option></select></label><label>Class<select name="classKey" id="dialogClass" required></select></label><label>Admission date<input name="admissionDate" type="date" max="${new Date().toISOString().slice(0,10)}" value="${esc(student.admission_date || '')}" ${isRestore?'disabled':''}></label><label>House<input name="house" maxlength="80" value="${esc(student.house || '')}" ${isRestore?'disabled':''}></label><label>Age<input name="age" maxlength="20" value="${esc(student.age || '')}" ${isRestore?'disabled':''}></label><label class="full">Photo path<input name="photo" maxlength="300" placeholder="Private storage path" value="${esc(student.photo || '')}" ${isRestore?'disabled':''}></label><div class="full panel-divider"><strong>Guardian data (actual school data only)</strong><small class="muted">Leave blank when no verified guardian information is available.</small></div><label>Guardian full name<input name="guardianFullName" maxlength="160" value="${esc(student.guardian?.fullName || '')}" ${isRestore?'disabled':''}></label><label>Relationship<input name="guardianRelationship" maxlength="80" placeholder="Parent / Guardian" value="${esc(student.guardian?.relationship || '')}" ${isRestore?'disabled':''}></label><label>Guardian phone<input name="guardianPhone" maxlength="40" value="${esc(student.guardian?.primaryPhone || '')}" ${isRestore?'disabled':''}></label><label>Guardian WhatsApp<input name="guardianWhatsappNumber" maxlength="40" value="${esc(student.guardian?.whatsappPhone || '')}" ${isRestore?'disabled':''}></label><label>Guardian email<input name="guardianEmail" type="email" maxlength="254" value="${esc(student.guardian?.email || '')}" ${isRestore?'disabled':''}></label><label class="check-row"><input name="guardianNotificationConsent" type="checkbox" ${student.guardian?.notificationConsent?'checked':''} ${isRestore?'disabled':''}> Notification consent</label>`;
  const select=$('#dialogClass');pagesLoadClasses(select,student.class_key);
  $('#recordForm').onsubmit=async(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());try{const result=await write(student.id?(isRestore?'students.restore':'students.update'):'students.create',student.id?(isRestore?{studentId:student.id,classKey:values.classKey}:{studentId:student.id,...values}):values);const studentId=result.studentId || student.id;if(values.guardianFullName && studentId)await write('guardian.upsert',{studentId,fullName:values.guardianFullName,relationship:values.guardianRelationship || 'Guardian',phone:values.guardianPhone,whatsappNumber:values.guardianWhatsappNumber,email:values.guardianEmail,isPrimary:true,isLegalGuardian:true,notificationConsent:values.guardianNotificationConsent==='on',preferredLanguage:'english'});dialog.close();}catch(error){$('#dialogError').textContent=error.code || error.message;}};dialog.showModal();
}
function openStudentArchiveDialog(student) {
  const dialog=$('#recordDialog');$('#dialogTitle').textContent='Archive student';$('#dialogError').textContent='';
  $('#dialogBody').innerHTML=`<p class="full muted">${esc(student.name || 'Student')} · ${esc(student.admno || student.class_key || '')}</p><label>Lifecycle status<select name="lifecycleStatus" required><option value="archived">Archived</option><option value="graduated">Graduated</option><option value="transferred">Transferred</option><option value="withdrawn">Withdrawn</option><option value="suspended">Suspended</option></select></label><label class="full">Reason<textarea name="reason" minlength="8" maxlength="500" required></textarea></label>`;
  $('#recordForm').onsubmit=async(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());try{await write('students.archive',{studentId:student.id,lifecycleStatus:values.lifecycleStatus,reason:values.reason});dialog.close();}catch(error){$('#dialogError').textContent=error.code || error.message;}};dialog.showModal();
}
async function pagesLoadClasses(select,value){try{const data=await registryRequest('read','catalog',{});(data.classes||[]).filter((item)=>item.is_active).forEach((item)=>select.append(new Option(item.display_name || item.class_key,item.class_key)));select.value=value || ''; }catch(error){showError(error);}}
async function handleStudentAction(event){const button=event.target.closest('[data-student-action]');if(!button)return;const id=button.dataset.studentId;const data=await registryRequest('read','student',{studentId:id});const student=data.students?.[0];if(!student)return;if(button.dataset.studentAction==='archive'){openStudentArchiveDialog(student);return;}const guardianData=await registryRequest('read','guardians',{studentId:id}).catch(()=>({guardians:[]}));const guardian=(guardianData.guardians||[]).find((item)=>item.isPrimary) || guardianData.guardians?.[0];openStudentDialog({...student,guardian},button.dataset.studentAction==='restore'?'restore':'edit');}
async function handleSignature(file){if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{await uploadSignature(reader.result,requestId());toast('Signature uploaded','success');resetCache();await loadContext();}catch(error){showError(error);}};reader.readAsDataURL(file);}
function reviewRegistration(registration,action){
  if(action==='under_review'){write('registration.under_review',{registrationId:registration.id}).catch(showError);return;}
  const dialog=$('#registrationDialog');const form=$('#registrationForm');const body=$('#registrationDialogBody');const error=$('#registrationDialogError');const approval=action==='registration.approve';
  $('#registrationDialogTitle').textContent=approval?'Approve staff registration':'Reject staff registration';$('#registrationDialogIntro').textContent=`${registration.full_name || 'Staff registration'} · ${registration.email || 'No email'}`;error.textContent='';
  body.innerHTML=approval?`<label>Staff category<select name="staffCategory" required><option value="teaching">Teaching</option><option value="non_teaching">Non-teaching</option><option value="management">Management</option><option value="contract">Contract</option><option value="casual">Casual</option></select></label><label>Designation<input name="designation" maxlength="160" required></label><label>Department<input name="department" maxlength="160"></label><label>School section<input name="schoolSection" maxlength="160"></label><label class="full">Approval reason<input name="reason" minlength="8" required value="Approved through Central Registry"></label>`:`<label class="full">Rejection reason<textarea name="reason" minlength="8" maxlength="500" required></textarea></label>`;
  form.onsubmit=async(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());try{await write(action,{registrationId:registration.id,...values});dialog.close();}catch(result){error.textContent=result.code || result.message;}};dialog.showModal();
}
function endAllocation(item,type){
  const dialog=$('#allocationEndDialog');const form=$('#allocationEndForm');const error=$('#allocationEndError');
  if(!dialog||!form)return;
  pendingAllocationEnd={item,type}; error.textContent=''; $('#allocationEndIntro').textContent=`${item.class_name || item.class_key || 'Allocation'} · ${item.subject_name || item.responsibility?.replaceAll('_',' ') || item.full_name || ''}`; $('#allocationEndReason').value='Allocation ended through Central Registry';
  form.onsubmit=async(event)=>{event.preventDefault();const reason=$('#allocationEndReason').value.trim();if(reason.length<8){error.textContent='ALLOCATION_REASON_REQUIRED';return;}try{const idField=type==='portfolio.assignment.end'?'assignmentId':'allocationId';await write(type,{[idField]:pendingAllocationEnd.item.id,reason});pendingAllocationEnd=null;dialog.close();}catch(result){error.textContent=result.code || result.message;}};dialog.showModal();
}

$('#loginForm').addEventListener('submit',async(event)=>{event.preventDefault();$('#authError').textContent='';try{const result=await sessionRequest({action:'login',login:$('#loginName').value.trim(),password:$('#loginPassword').value});if(result.must_change_password){$('#authError').textContent='Password change is required. Use Forgot or set password before entering Registry.';return;}applyContext(result.context || await getSession());await loadRoute('dashboard',true);}catch(error){$('#authError').textContent=error.code || error.message;}});
$('#signOutButton').addEventListener('click',async()=>{try{await sessionRequest({action:'logout'});}catch{/* cookie is cleared locally */}lock();});
$('#refreshButton').addEventListener('click',()=>loadContext().catch(showError));
$$('[data-route]').forEach((button)=>button.addEventListener('click',()=>loadRoute(button.dataset.route)));
$('#studentSearchButton').addEventListener('click',()=>{pages.invalidate('students');pages.loadStudents().catch(showError);});$('#studentStatus').addEventListener('change',()=>{pages.invalidate('students');pages.loadStudents().catch(showError);});$('#studentClass').addEventListener('change',()=>{pages.invalidate('students');pages.loadStudents().catch(showError);});$('#studentRows').addEventListener('click',handleStudentAction);$('#newStudentButton').addEventListener('click',()=>openStudentDialog());
$('#selfProfileForm').addEventListener('submit',async(event)=>{event.preventDefault();const payload={phone:$('#selfPhone').value.trim(),whatsappNumber:$('#selfWhatsapp').value.trim(),address:$('#selfAddress').value.trim(),emergencyContact:$('#selfEmergency').value.trim(),photo:$('#selfPhoto').value.trim()};await write('profile.self.update',payload);});$('#signatureFile').addEventListener('change',(event)=>handleSignature(event.target.files?.[0]));$('#staffSearchButton').addEventListener('click',()=>{pages.invalidate('staff');pages.loadStaff().catch(showError);});
$('#registrationRefresh').addEventListener('click',()=>{pages.invalidate('registrations');pages.loadRegistrations().catch(showError);});$('#registrationStatus').addEventListener('change',()=>{pages.invalidate('registrations');pages.loadRegistrations().catch(showError);});$('#allocationRefresh').addEventListener('click',()=>{pages.invalidate('catalog');pages.invalidate('allocations');pages.loadAllocations().catch(showError);});$('#subjectClass').addEventListener('change',async()=>{const data=await registryRequest('read','catalog',{});pages.renderSubjects(data.subjects||[],$('#subjectClass').value);});
$('#classAllocationForm').addEventListener('submit',async(event)=>{event.preventDefault();await write('allocations.class.set',{classKey:$('#allocationClass').value,staffId:$('#allocationStaff').value,responsibility:$('#allocationResponsibility').value,reason:$('#allocationReason').value.trim()});});$('#subjectAllocationForm').addEventListener('submit',async(event)=>{event.preventDefault();const subjectIndexes=$$('#subjectChoices input:checked').map((input)=>Number(input.value));await write('allocations.subject.set',{classKey:$('#subjectClass').value,staffId:$('#subjectStaff').value,subjectIndexes,reason:$('#subjectReason').value.trim()});});
$('#accessSearchButton').addEventListener('click',()=>{pages.invalidate('portal_access');pages.loadPortalAccess().catch(showError);});$('#calendarRefresh').addEventListener('click',()=>{pages.invalidate('calendar');pages.loadCalendar().catch(showError);});$('#transitionForm').addEventListener('submit',async(event)=>{event.preventDefault();const result=await write('calendar.transition',{sourceSession:$('#sourceSession').value.trim(),sourceTerm:state.context?.academicContext?.term || '3rd Term',targetSession:$('#targetSession').value.trim(),targetTerm:'1st Term',reason:$('#transitionReason').value.trim(),confirmed:$('#transitionConfirm').checked});const transitionRunId=result.run_id || result.transitionRunId || result.transition_run_id;if(transitionRunId)$('#prefectTransitionRunId').value=transitionRunId;});$('#openPrefectCycle').addEventListener('click',async()=>{const source=state.context?.academicContext?.session || '';const target=source.replace(/^(\d{4})\/(\d{4})$/,(_,a,b)=>`${Number(a)+1}/${Number(b)+1}`);await write('prefect.open',{academicSession:source,targetSession:target,reason:'Annual Student Executive Council selection'});});$('#approvePrefectCycle').addEventListener('click',async()=>{const first=state.cache.get('prefect:{}')?.cycles?.[0];if(first)await write('prefect.approve',{cycleId:first.id});});$('#activatePrefectCycle').addEventListener('click',async()=>{const transitionRunId=$('#prefectTransitionRunId').value.trim();if(transitionRunId)await write('prefect.activate',{transitionRunId});});$('#portfolioCode').addEventListener('change',()=>pages.syncPortfolioForm());$('#portfolioHolderType').addEventListener('change',()=>pages.syncPortfolioForm());$('#portfolioAssignmentForm').addEventListener('submit',async(event)=>{event.preventDefault();await write('portfolio.assignment.set',{portfolioCode:$('#portfolioCode').value,holderType:$('#portfolioHolderType').value,staffId:$('#portfolioStaff').value,studentId:$('#portfolioStudent').value,scopeType:$('#portfolioScopeType').value,stageCode:$('#portfolioStage').value,classKey:$('#portfolioClass').value,reason:$('#portfolioReason').value.trim()});});
$('#resultsOperatingForm').addEventListener('submit',async(event)=>{event.preventDefault();const button=$('#resultsOperatingToggle');await write('portal.operating_mode.set',{appCode:'results',operatingMode:button.dataset.nextMode,reason:$('#resultsOperatingReason').value.trim()});$('#resultsOperatingReason').value='';});

window.RegistryApp={write,loadRoute,reviewRegistration,endAllocation,get selectedPersonId(){return selectedPersonId;},set selectedPersonId(value){selectedPersonId=value;}};
async function bootstrap(){
  try{
    const exchanged=await exchangeSsoCallback();
    if(exchanged?.ok){applyContext(exchanged.context || await getSession());await loadRoute('dashboard',true);return;}
    try{const context=await getSession();applyContext(context);await loadRoute('dashboard',true);return;}catch{/* no Registry cookie yet */}
    lock();
    if(new URLSearchParams(window.location.search).get('sso')==='1')await beginSso();
  }catch(error){clearSsoTransaction();$('#authError').textContent=error.code || error.message || 'SSO sign-in failed';lock();}
}
bootstrap();
